apiVersion: v1
kind: Service
metadata:
  name: raghucapstoneprj
#  namespace: eks-capstone-ns
  labels:
    app: raghucapstoneprj
spec:
  type: LoadBalancer
  selector:
    app: raghucapstoneprj
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80